## Grants, Fellowships, and Awards  
2021: Co-author, Mellon Foundation Grant #2101-09956, for the Black Lunch Table Digital  Archive (PI: Jina Valentine), $500,000  
  
2021: Co-author, NEH Digital Humanities Advancement Level III Grant #HAA-280677-21,  for Sinai Manuscripts Data Portal Project (PIs: Virginia Steel and Dawn Childress),  $325,000  
  
2020: Co-author, The Andy Warhol Foundation for the Visual Arts, for the Black Lunch Table  (PI: Jina Valentine), $60,000  
  
2019: Digital Atlas Design Internship course selected as one of four University of Pittsburgh  entries to the ACC Smithsonian Creativity and Innovation Festival, National Museum of  American History, Washington, D.C, April 5-7  
  
2018: WikiConference North America 2018 Scholarship  
  
2018: NEH-Mellon Fellowship for Digital Publication #FEL-257341-18, $50,400  
  
2015: Co-author, Obermann Center for Advanced Studies Interdisciplinary Research Grant,  University of  Iowa  
  
2014: Holsenbeck Fund, University of North Carolina, Chapel Hill  
  
2013: Raymond Faherty Research Grant for Military History, University of North Carolina,  Chapel Hill  
  
2013: George B. Tindall Graduate Fellowship for Summer Research, University of North  Carolina, Chapel Hill  
  
2013: Semple Award, Classical Association of the Middle West and South  
  
2012:  Wadell Fund, University of North Carolina Chapel Hill  
  
2012: Mowry Dissertation Fellowship, University of North Carolina Chapel Hill  
  
2011: Clein Fund, University of North Carolina Chapel Hill  
  
2009: Drake Fund, University of California, Santa Barbara  