## Professional Experience  
2022 - present: Research Consultant, Office of Advanced Research Computing, University of California, Los Angeles

2021 - 2022: Digital Humanities Research Facilitator, Research Data Services, University of California, Santa Barbara Library

2020 - 2021: Sinai Manuscripts Digital Library Data/Metadata Coordinator, Digital Library Program, University of California, Los Angeles Digital Library Program

2019 - 2020: Research Associate, World History Center, History Department, University of Pittsburgh

2017 - 2019: Post-Doctoral Fellow, World History Center, History Department, University of Pittsburgh

2015 - 2017: Post-Doctoral Fellow, the Carolina Digital Humanities Initiative, History Department, and the Institute for the Arts and Humanities, University of North Carolina, Chapel Hill

2014 - 2015: Director, Ancient World Mapping Center, History Department, University of North Carolina, Chapel Hill

2010 - 2014: Digital Director, Ancient World Mapping Center, History Department, University of North Carolina, Chapel Hill

2008 - 2010: Teaching Assistant, University of California, Santa Barbara

2005 - 2007: Software Engineer Associate, Lockheed Martin, Owego, NY  
(Developed optical character recognition software and web resources)